### ISSUE TITLE
diod building error (according to build instrucctions)

### ISSUE THREAD

**Issue by argento-ar** [Rudd-O/qubes-shared-folders#1]
Sup my man!!
Before anything, i want to thank you for this, is a much needed feature (that should be included by default (or optional, at least) with the default qubes instalation. Thanks !!!

Im a linux user only, not developer, the little i know, was learned bashing my head to the wall, i really don't know if the process described below, is the correct one, please confirm it , (and correct the README.md help, with the correct process, no mather what) .

**Error** :
according to the docs, for building diod, on a disp machine (fc34) you need to install 'munge-devel' and 'ncurses-devel' , then , on the build process , the final step is 'rpmbuild -ts *tar.gz'
Using that instruccions, i can´t make it to work , there where missing dependencies, and after fixing that deps, only a '.src.rpm' where generated, no binaries.

**Fix?**
_missing dependencies_: (default fedora-34 qubes template , running under qubes 4.0 (fully updated)
'autoconf automake lua-devel rpm-build libattr-devel libcap-devel' (the last two needed for the rpmbuild step to complete w/o errors)

_rpm build step_
the '-ts'  flag , generates only the *.src.rpm , not the bin one, needed to change that flag for '-ta' , then the .rm bin is generated

Idk if the steps i did for generating the diod install rpm's without error are valid, i think so, but not fully convinced, i will use the rpm's you put on the releases in the meantime.
(https://rudd-o.com/uploads/projects/files/qubes-shared-folders)

Thanks in advance, and happy holidays
Alvaro

**Comment by Rudd-O** [comment]
Thanks.  I have amended the instructions so they work as you noted.  Will upload new packages to the qubes-shared-folders directory.
