### ISSUE TITLE
Qubes 4.1 default install issue

### ISSUE THREAD

**Issue by NN-Binary** [Rudd-O/qubes-shared-folders#10]
Hi,

I've just freshly installed Qubes 4.1, it's with Fedora 37 in default template, followed the procedure but when reaching dom0 to install the final RPM package:

`qubes-shared-folders-0.1.3-1.fc37.noarch.rpm` file, built without problem using toolbox, then I copied that file to `dom0` (no issue)

Now, in `dom0`, it says:
- nothing provides qubes-core-agent-qrexec needed by qubes-shared-folders-0.1.3-1.fc37.noarch.rpm|

qubes-core-agent-qrexec is no where to be found, I can't find an RPM for it too, I've searched for a while but no solution as of now and I really want to use your repo.

Thank you for the help

**Comment by Rudd-O** [comment]
You are not following the instructions correctly.  That package is to be installed in your template.   The `qubes-shared-folders-dom0` package must be installed in your dom0 — and it must also be built in a Fedora 32 VM / toolbox.

**Comment by NN-Binary** [comment]
> You are not following the instructions correctly. That package is to be installed in your template. The `qubes-shared-folders-dom0` package must be installed in your dom0 — and it must also be built in a Fedora 32 VM / toolbox.

This is what I said, I've built it with the Toolbox in a template, copied to dom0 and then attempt to install `qubes-shared-folders-dom0` in `dom0`, and then there is `qubes-core-agent-qrexec ` that simply does not exist in `dom0`

**Comment by Rudd-O** [comment]
Package `qubes-shared-folders-dom0` does not require `qubes-core-agent-qrexec` at all.  It requires package `qubes-core-dom0-linux` in Fedora 32 Qubes flavor.  `qubes-core-agent-qrexec` is a requirement of package `qubes-shared-folders`, and is provided by Fedora 37 template package `qubes-core-qrexec-vm`.
