### ISSUE TITLE
Followed instructions to the letter but it doesn't work?

### ISSUE THREAD

**Issue by LEOcab** [Rudd-O/qubes-shared-folders#3]
I get this error when running the qvm-mount-folder command: Unknown error

I don't know what I did wrong, or where to begin debugging this. Can someone lend me a hand?

**Comment by Rudd-O** [comment]
I am sorry but I need way more information to reproduce your issue — look at the `journalctl` logs of the target and the source VM, look at dom0 logs.  I cannot reproduce otherwise.
