### ISSUE TITLE
debian11

### ISSUE THREAD

**Issue by NA3** [Rudd-O/qubes-shared-folders#4]
hi, this can be use for debian 11 template?
i can manage to get the server side on a fedora template, but i have debian, arch and windows client who need to connect to server.
can you explain how can i make this client side binary?
Regards

**Comment by Rudd-O** [comment]
The 9P file system is not implemented for Windows, so you won't be able to make that work there.

The client package will work in a Debian VM (run `make install-client`) so long as you have the following Debian packages installed (not sure about their names):

* [desktop-file-utils](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=desktop-file-utils)
* Python 3
* [diod](https://packages.debian.org/search?searchon=sourcenames&keywords=diod)
