### ISSUE TITLE
A problem with the original diod

### ISSUE THREAD

**Issue by EnDelta** [Rudd-O/qubes-shared-folders#7]
Getting an error (the diod's help prompt) when trying to mount a shared folder. ~~That's not a joke.~~

### To Reproduce:
Just use the original diod.
I followed the installation instructions for a Debian template and just installed the diod with `sudo apt install diod` command.

### Fix:
Remove the `-H` parameter in **_etc/qubes-rpc/ruddo.ConnectToFolder_** from the line 41
```bash
exec /usr/sbin/diod -f -r 0 -w 1 -n -e "$requested_folder" -S || {
```

**Comment by Rudd-O** [comment]
We need the `-H` — it's not optional because it doesn't work well in Fedora without it.

Let me see what I can do.
